name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up QMake
      uses: qt-actions/setup-qmake@v1
      
    - name: Install dependencies
      run: sudo apt-get install -y build-essential qt5-default
      
    - name: Build project
      run: qmake && make
      
    - name: Run program
      run: ./QtPuppies
